id: /starknets-security
title: Starknet’s security
template: content
breadcrumbs: true
page_last_updated: true
blocks:
  - type: page_header
    title: Starknet's security
blocks:
  - type: markdown
    body: >-
      Starknet’s security
